### PR TITLE
Pass argc as reference to reinitializeAsQApplication (fixes #3367)

### LINKED ISSUE #3367: [Debian testing crashed] exec 'flameshot gui' in debian testing distro, crashed by Segmentation Fault
### Flameshot Version

Flameshot 12.1.0 and master branch

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Debian testing

### Description

Installed the Flameshot 12.1.0 in testing version, when I exec 'flameshot gui', output:
**_QLayout: Attempting to add QLayout "" to SidePanelWidget "", which already has a layout
Segmentation fault_**

then I pull the master branch and compile in locally and meet the same issues.
_m75t@debian:~/Downloads$ flameshot gui
QLayout: Attempting to add QLayout "" to SidePanelWidget "", which already has a layout
Segmentation fault
m75t@debian:~/Downloads$_

### Steps to reproduce

1. install or compile from source code, v12.1.0 and master branch
2. run 'flameshot gui'
3. crashed -> QLayout: Attempting to add QLayout "" to SidePanelWidget "", which already has a layout
Segmentation fault

### Screenshots or screen recordings

flameshot-gui

### System Information

m75t@debian:~/Downloads$ uname -a
Linux debian 6.4.0-3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.4.11-1 (2023-08-17) x86_64 GNU/Linux

Monitor:

monitor

### PR DESCRIPTION
**Pull request by marceldev89**
Fixes crash caused by https://github.com/flameshot-org/flameshot/pull/3313

### CODE REVIEW

File: src/main.cpp [hunk 1]
```diff
@@ -117,7 +117,7 @@ void configureApp(bool gui)
 
 // TODO find a way so we don't have to do this
 /// Recreate the application as a QApplication
-void reinitializeAsQApplication(int argc, char* argv[])
+void reinitializeAsQApplication(int &argc, char* argv[])
```
Comment (veracioux) [inline src/main.cpp:120]: @marceldev89 Nice catch. Though it looks to me that `argv` could fail in the same way. Can you replace it with `char *(&argv)[]`?

Comment (marceldev89) [reply src/main.cpp:120]: @veracioux it shouldn't. The problem was that the `QApplication` constructor signature which is `QApplication(int &argc, char **argv)`. So it expects a reference to `argc` instead of the value. `argv` should be fine as `char* argv[]` is basically the same as `char **argv` I think :)

Comment (veracioux) [reply src/main.cpp:120]: @marceldev89 Yup, very subtle and annoying. Please do a [clang-format](https://github.com/flameshot-org/flameshot/blob/master/docs/CONTRIBUTING.md#code) on the code, so our pipeline can pass before merge.

Comment (marceldev89) [reply src/main.cpp]: Done :)

**Review by veracioux — APPROVED** [review]

File: src/main.cpp (hunk 1 above)
Comment (veracioux) [reply src/main.cpp]: Thank you! Merging.
